cask_args appdir: '/Applications'
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-drivers'
tap 'buo/cask-upgrade'
tap "universal-ctags/universal-ctags"

# Homebrew
brew 'bat'
brew 'composer'
brew 'curl'
brew 'dokku'
brew 'exa'
brew 'fd'
brew 'ffmpeg'
brew 'fzf'
brew 'git'
brew 'go'
brew 'gotop'
brew 'gping'
brew 'httpie'
brew 'hugo'
brew 'java'
brew 'jq'
brew 'lazydocker'
brew 'lazygit'
brew 'lesspipe'
brew 'm-cli'
brew 'mas'
brew 'node'
brew 'pandoc'
brew 'php'
brew 'prettyping'
brew 'python@3'
brew 'reattach-to-user-namespace'
brew 'ripgrep'
brew 'sqlite'
brew 'ssh-copy-id'
brew 'starship'
brew 'tldr'
brew 'tmux'
brew 'trash'
brew 'universal-ctags', args: ['HEAD']
brew 'vim'
brew 'webp'
brew 'wget'
brew 'youtube-dl'
brew 'zsh'
brew 'zsh-syntax-highlighting'
brew 'zsh-history-substring-search'

# Casks
## Apps
cask '1password'
cask 'acorn'
cask 'aerial'
cask 'alfred'
cask 'bartender'
cask 'bettertouchtool'
cask 'calibre'
cask 'colorpicker-developer'
cask 'colorpicker-skalacolor'
cask 'contexts'
cask 'daisydisk'
cask 'dash'
cask 'devonthink'
cask 'discord'
cask 'docker'
cask 'dropbox'
cask 'firefox'
cask 'font-jetbrains-mono'
cask 'hazel'
cask 'istat-menus'
cask 'item2'
cask 'jetbrains-toolbox'
cask 'kaleidoscope'
cask 'keyboard-maestro'
cask 'mactex'
cask 'marked'
cask 'omnifocus'
cask 'pdfpenpro'
cask 'private-internet-access'
cask 'qlcolorcode'
cask 'qlmarkdown'
cask 'qlstephen'
cask 'quicklook-csv'
cask 'quicklook-json'
cask 'screens-connect'
cask 'simple-comic'
cask 'slack'
cask 'soulver'
cask 'superduper'
cask 'tableplus'
cask 'telegram'
cask 'textexpander'
cask 'the-unarchiver'
cask 'tower'
cask 'transmission'
cask 'transmit'
cask 'ttscoff-mmd-quicklook'
cask 'visual-studio-code'
cask 'vlc'
cask 'vmware-fusion'
cask 'yubico-yubikey-piv-manager'
cask 'zsa-wally'

# Mac App Store
mas '1Blocker for Safari', id:1107421413
mas 'Amphetamine', id:937984704
mas 'Day One', id:1055511498
mas 'Deliveries', id:924726344
mas 'Drafts' id:1435957248
mas 'Due', id:524373870
mas 'Home Inventory', id:413564952
mas 'iFlicks 3', id: 1274494218
mas 'Microsoft Remote Desktop 10', id:1295203466
mas 'Numbers', id:409203825
mas 'Paprika Recipe Manager 3', id:1303222628
mas 'StopTheMadness', id:1376402589
mas 'Streaks', id:1493327990
