[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
opacity = 0.9
blur = true
startup_mode = "Maximized"
option_as_alt = "Both"

[font]
size = 18.0

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Heavy"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Heavy Italic"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Medium Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Medium"

[general]
import = ["~/.config/alacritty/dracula_plus.toml"]
